#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/__SED_DISCOVERY_TOKEN__
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4
    metadata: name=__SED_NAME__,size=__SED_SIZE__
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
